# Generated by Django 3.0.8 on 2020-08-01 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Desiger',
            new_name='Designer',
        ),
    ]
